// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  call_to_action: dynamic(() => import("./CallToAction")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
};
